import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SocketContextProvider from '../context/socket.context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <meta httpEquiv='Permissions-Policy' content='interest-cohort=()' />
      <body className={inter.className + ' w-screen h-screen'}>
        <SocketContextProvider>{children}</SocketContextProvider>
      </body>
    </html>
  )
}
